
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compi1.web_designer_api.htmltraductor;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int BORRAR_PAGINA = 14;
  public static final int ALINEACION = 30;
  public static final int PAGINA = 25;
  public static final int PARAMETROS = 10;
  public static final int EQUALS = 49;
  public static final int NOMBRE = 8;
  public static final int ANCHO = 32;
  public static final int IZQUIERDA = 44;
  public static final int VIDEO = 40;
  public static final int ETIQUETAS = 7;
  public static final int MENU = 41;
  public static final int FINISHER = 47;
  public static final int CENTRAR = 42;
  public static final int TITULO_CLASS = 37;
  public static final int TITULO = 27;
  public static final int STRING_TKN = 54;
  public static final int PADRE = 24;
  public static final int ID = 23;
  public static final int COLOR_HEX = 55;
  public static final int NUEVA_PAGINA = 18;
  public static final int EOF = 0;
  public static final int BORRAR_COMPONENTE = 13;
  public static final int CLASE = 20;
  public static final int error = 1;
  public static final int INTEGER_TKN = 53;
  public static final int FECHA_MODIFICACION = 22;
  public static final int ATRIBUTOS = 5;
  public static final int BORRAR_SITIO_WEB = 15;
  public static final int ATRIBUTO = 4;
  public static final int ACCION = 2;
  public static final int COLOR = 33;
  public static final int USUARIO_MODIFICACION = 29;
  public static final int FECHA_CREACION = 21;
  public static final int NUEVO_SITIO_WEB = 19;
  public static final int USUARIO_CREACION = 28;
  public static final int NAV_INPUT = 52;
  public static final int VALOR = 11;
  public static final int DERECHA = 43;
  public static final int IMAGEN = 39;
  public static final int PARRAFO = 38;
  public static final int ORIGEN = 35;
  public static final int MODIFICAR_COMPONENTE = 16;
  public static final int ETIQUETAS_MENU = 34;
  public static final int OPEN = 46;
  public static final int AGREGAR_COMPONENTE = 12;
  public static final int PARAMETRO = 9;
  public static final int ACCIONES = 3;
  public static final int SITIO = 26;
  public static final int CLOSE = 48;
  public static final int TEXTO = 36;
  public static final int ETIQUETA = 6;
  public static final int JUSTIFICAR = 45;
  public static final int ALTURA = 31;
  public static final int DATE_TKN = 50;
  public static final int MODIFICAR_PAGINA = 17;
  public static final int IDENTIFIER = 51;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ACCION",
  "ACCIONES",
  "ATRIBUTO",
  "ATRIBUTOS",
  "ETIQUETA",
  "ETIQUETAS",
  "NOMBRE",
  "PARAMETRO",
  "PARAMETROS",
  "VALOR",
  "AGREGAR_COMPONENTE",
  "BORRAR_COMPONENTE",
  "BORRAR_PAGINA",
  "BORRAR_SITIO_WEB",
  "MODIFICAR_COMPONENTE",
  "MODIFICAR_PAGINA",
  "NUEVA_PAGINA",
  "NUEVO_SITIO_WEB",
  "CLASE",
  "FECHA_CREACION",
  "FECHA_MODIFICACION",
  "ID",
  "PADRE",
  "PAGINA",
  "SITIO",
  "TITULO",
  "USUARIO_CREACION",
  "USUARIO_MODIFICACION",
  "ALINEACION",
  "ALTURA",
  "ANCHO",
  "COLOR",
  "ETIQUETAS_MENU",
  "ORIGEN",
  "TEXTO",
  "TITULO_CLASS",
  "PARRAFO",
  "IMAGEN",
  "VIDEO",
  "MENU",
  "CENTRAR",
  "DERECHA",
  "IZQUIERDA",
  "JUSTIFICAR",
  "OPEN",
  "FINISHER",
  "CLOSE",
  "EQUALS",
  "DATE_TKN",
  "IDENTIFIER",
  "NAV_INPUT",
  "INTEGER_TKN",
  "STRING_TKN",
  "COLOR_HEX"
  };
}

